[package]
name = "resox"
version = "0.1.0"
authors = ["Cristi Cismas <cristicismas99@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.10"
